USE [ALVESESILVA]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF OBJECT_ID('Pessoa', 'U') IS NOT NULL
DROP TABLE [Pessoa]

CREATE TABLE [Pessoa](
	[idPessoa] [int] IDENTITY(1,1) NOT NULL,
    [idTenant] [int] NULL,
	[Nome] [varchar](140) NOT NULL,
	[Email] [varchar](140) NULL,
	[Senha] [char](64) NULL,
	[DataCad] [datetime] NOT NULL,
    [Ativo] [bit] NOT NULL,
 CONSTRAINT [IdTenant] PRIMARY KEY CLUSTERED 
(
	[idPessoa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO